import { useState } from "react";
import Image from "next/image";
import { FaFacebookF, FaTwitter, FaInstagram } from "react-icons/fa";
import Card from "@mui/material/Card";
import CardActionArea from "@mui/material/CardActionArea";
import CardMedia from "@mui/material/CardMedia";
import CardContent from "@mui/material/CardContent";
import Typography from "@mui/material/Typography";
import Head from "next/head";
import portpfp from "../public/portpfp.png";
import hobbies from "../public/hobbies.png";
import interests from "../public/interests.png";
import more from "../public/more.png";
import web1 from "../public/web1.jpg";
import web2 from "../public/web2.jpg";
import web3 from "../public/web3.jpg";
import web4 from "../public/web4.jpg";
import web5 from "../public/web5.jpg";
import web6 from "../public/web6.jpg";

const Home = () => {
  const [darkMode, setDarkMode] = useState(false);

  const cardContents = [
    {
      title: "Elementary",
      image: { src: "/elem.png", alt: "Elementary School" },
    },
    {
      title: "High School",
      image: { src: "/hs.png", alt: "High School" },
    },
    {
      title: "College",
      image: { src: "/college.png", alt: "College" },
    },
  ];

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>ITCC40Final</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">portfolio</h1>
            <ul className="flex items-center">
              <li>
                <button
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  onClick={() => setDarkMode(!darkMode)}
                >
                  Light/Dark
                </button>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Scott Renzo Baban
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              BSCS - 3 Student
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              This is a glimpse into my journey, experiences, and passions. Join
              me as I share my story and showcase my growth as a student. Let's
              connect and explore the possibilities together!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                href="https://www.facebook.com/scottybbn/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <FaFacebookF />
              </a>
              <a
                href="https://twitter.com/iskatiboi"
                target="_blank"
                rel="noopener noreferrer"
              >
                <FaTwitter />
              </a>
              <a
                href="https://www.instagram.com/scottbaban/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <FaInstagram />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={portpfp} alt="Description of the image" layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section className="mt-20">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">
              Educational Background
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I embarked on an educational journey from elementary school to
              becoming a
              <span className="text-teal-500">
                {" "}
                3rd-year Computer Science student{" "}
              </span>
              at <span className="text-teal-500"> Xavier University</span>,
              continuously growing and thriving in the field.
            </p>
          </div>
          <div className="flex justify-center">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-20">
              {cardContents.map((content, index) => (
                <Card key={index} sx={{ maxWidth: 345 }}>
                  <CardActionArea>
                    <CardMedia
                      component="img"
                      height="140"
                      image={content.image.src}
                      alt="Ctto"
                      style={{ objectFit: "cover" }}
                    />
                    <CardContent>
                      <Typography
                        gutterBottom
                        variant="h5"
                        component="div"
                        textAlign="center"
                      >
                        {content.title}
                      </Typography>
                      <Typography
                        variant="body2"
                        color="text.secondary"
                        textAlign="center"
                      >
                        {content.description}
                      </Typography>
                    </CardContent>
                  </CardActionArea>
                </Card>
              ))}
            </div>
          </div>
        </section>

        <section className="mt-20">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Hobbies/Interests/Etc.</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Apart from my academic pursuits, I have a diverse range of hobbies and interests that keep me inspired and balanced. 
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            From exploring different genres of music to delving into the world of gaming, I find joy in the richness of these experiences.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={hobbies} alt="Description of the image" width={200} height={200} />
              <h3 className="text-lg font-medium pt-8 pb-2  text-teal-600 ">
                Hobbies
              </h3>
              <p className="py-2">
              I find solace and joy in pursuing my hobbies. They allow me to unwind, express myself, and discover new passions.
              </p>
              <p className="text-gray-800 py-1">Play Guitar</p>
              <p className="text-gray-800 py-1">Play or Watch Basketball</p>
              <p className="text-gray-800 py-1">Eating lol</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={interests} alt="Description of the image" width={200} height={200} />
              <h3 className="text-lg font-medium pt-8 pb-2  text-teal-600 ">
                Interests
              </h3>
              <p className="py-2">
              Curiosity drives me to explore various interests 
              and expand my knowledge. 
              </p>

              <p className="text-gray-800 py-1">Kpop</p>
              <p className="text-gray-800 py-1">Kdrama</p>
              <p className="text-gray-800 py-1">Computers</p>
              <p className="text-gray-800 py-1"></p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={more} alt="Description of the image" width={200} height={200} />
              <h3 className="text-lg font-medium pt-8 pb-2  text-teal-600 ">Etc.</h3>
              <p className="py-2">
                Etc. Just etc. things.
              </p>
              <p className="text-gray-800 py-1">Know a little about Java/JavaScript/Python</p>
              <p className="text-gray-800 py-1">Know a little about business</p>
              <p className="text-gray-800 py-1">Procrastinates every little thing</p>
              <p className="text-gray-800 py-1">Part-time Student, Full-time Crammer</p>
            </div>
          </div>
        </section>

        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Pictures</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                alt="Description of the image"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
                alt="Description of the image"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
                alt="Description of the image"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
                alt="Description of the image"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
                alt="Description of the image"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
                alt="Description of the image"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
